//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public int creq_id { get; set; }
        public int creq_r_id { get; set; }
        public int creq_f_id { get; set; }
        public System.DateTime creq_max_time { get; set; }
        public string creq_status { get; set; }
        public Nullable<int> creq_e_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Resturant Resturant { get; set; }
        public virtual Food Food { get; set; }
    }
}
