//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.CollectRequests = new HashSet<CollectRequest>();
        }
    
        public int e_id { get; set; }
        public string e_name { get; set; }
        public string e_location { get; set; }
        public string e_designation { get; set; }
    
        public virtual ICollection<CollectRequest> CollectRequests { get; set; }
    }
}
