//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.Resturants = new HashSet<Resturant>();
            this.CollectRequests = new HashSet<CollectRequest>();
        }
    
        public int f_id { get; set; }
        public string f_name { get; set; }
    
        public virtual ICollection<Resturant> Resturants { get; set; }
        public virtual ICollection<CollectRequest> CollectRequests { get; set; }
    }
}
