//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resturant
    {
        public Resturant()
        {
            this.CollectRequests = new HashSet<CollectRequest>();
        }
    
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string r_address { get; set; }
        public int food_id { get; set; }
    
        public virtual ICollection<CollectRequest> CollectRequests { get; set; }
        public virtual Food Food { get; set; }
    }
}
